"""teragent.core.adapters.mock — Mock TAP Adapter

Local testing adapter that simulates model responses without network I/O.
Used for CI environments, unit tests, and development.

Features:
  - Configurable delay and failure rate
  - Intent-aware mock responses based on CompiledPrompt content
  - Streaming simulation (yields chunks with small delays)
"""

from __future__ import annotations

import asyncio
import logging
import random
from typing import AsyncIterator

from teragent.core.adapter import TAPAdapter, TAPAdapterRegistry
from teragent.core.tap import CompiledPrompt, TAPResponse

logger = logging.getLogger(__name__)


class MockAdapter(TAPAdapter):
    """Mock adapter for TAP — simulates model responses for local testing

    No network I/O is performed. Responses are generated based on the
    intent detected in the CompiledPrompt content.

    Args:
        delay: Simulated response latency in seconds (default 0.1)
        fail_rate: Probability of simulated failure, 0.0–1.0 (default 0.0)
    """

    def __init__(
        self,
        delay: float = 0.1,
        fail_rate: float = 0.0,
    ) -> None:
        self.delay = delay
        self.fail_rate = fail_rate
        self._call_count = 0

        logger.info(
            f"MockAdapter: delay={self.delay}s, fail_rate={self.fail_rate}"
        )

    # ----- intent detection -----

    @staticmethod
    def _detect_intent(compiled: CompiledPrompt) -> str:
        """Detect the intent from CompiledPrompt content for mock response selection.

        Inspects Mode A messages or Mode B system_prompt/user_message for
        intent keywords. Falls back to "code_generation".
        """
        # Collect all text content from the compiled prompt
        all_text_parts: list[str] = []

        # Mode A: messages
        if compiled.messages:
            for msg in compiled.messages:
                all_text_parts.append(msg.get("content", ""))

        # Mode B: system_prompt + user_message
        if compiled.system_prompt:
            all_text_parts.append(compiled.system_prompt)
        if compiled.user_message:
            all_text_parts.append(compiled.user_message)

        all_content = " ".join(all_text_parts)

        # Match intents — check more specific patterns first
        if (
            "生成 PLAN" in all_content
            or "拆解" in all_content
            or "PLAN.md" in all_content
        ):
            return "plan"
        if "APPROVE" in all_content or "审核" in all_content or "审查" in all_content:
            return "review"
        if "核对" in all_content or "checklist" in all_content.lower():
            return "checklist"
        if (
            "需求" in all_content
            or "DESIGN" in all_content
            or "设计" in all_content
        ):
            return "design"
        return "code_generation"

    @staticmethod
    def _get_mock_response(intent: str, task_id: str = "unknown") -> str:
        """Return a mock response based on the detected intent."""
        mock_responses: dict[str, str] = {
            "design": (
                "# DESIGN\n"
                "## 1. Background & Motivation\n"
                "Mock design document.\n"
                "## 2. Design Goals\n"
                "| Goal | Description |\n"
                "|------|-------------|\n"
                "| Usability | System works correctly |\n"
                "## 3. Tech Stack\n"
                "Python + asyncio\n"
                "## 4. Core Interface Contract\n"
                "```python\n"
                "class MockSystem:\n"
                "    async def run(self) -> None: ...\n"
                "```"
            ),
            "plan": (
                "### 1.1 Implement core module\n"
                "- **Prerequisites**: None\n"
                "- **Output files**: mock_module.py\n"
                "- **Priority**: Required\n\n"
                "### 1.2 Implement tests\n"
                "- **Prerequisites**: 1.1\n"
                "- **Output files**: test_mock.py\n"
                "- **Priority**: Optional"
            ),
            "review": "APPROVE",
            "checklist": (
                "- [x] 1.1 Implement core module\n"
                "- [ ] 1.2 Implement tests"
            ),
            "code_generation": (
                f'<file path="mock_output.py">\n'
                f"# Auto-generated by MockAdapter\n"
                f"def main() -> None:\n"
                f'    """Mock implementation for task: {task_id}"""\n'
                f"    pass\n"
                f"</file>"
            ),
        }
        return mock_responses.get(intent, mock_responses["code_generation"])

    # ----- core send -----

    async def send(self, compiled: CompiledPrompt, model: str) -> TAPResponse:
        """Send a compiled prompt to the mock adapter.

        Simulates delay and possible failure. Returns a mock TAPResponse
        based on the detected intent in the prompt content.
        """
        self._call_count += 1
        await asyncio.sleep(self.delay)

        if random.random() < self.fail_rate:
            raise RuntimeError("MockAdapter simulated failure")

        intent = self._detect_intent(compiled)

        # Check messages for task_id keyword (Mode A); use a placeholder if found
        task_id = "unknown"
        if compiled.messages:
            for msg in compiled.messages:
                content = msg.get("content", "")
                # Placeholder: real extraction would parse the actual task_id value
                if "task_id" in content:
                    task_id = "mock_task"

        raw_text = self._get_mock_response(intent, task_id)

        # Simulate token usage estimation
        prompt_text = ""
        if compiled.messages:
            prompt_text = " ".join(
                msg.get("content", "") for msg in compiled.messages
            )
        else:
            prompt_text = (
                f"{compiled.system_prompt} {compiled.user_message}"
            )

        prompt_tokens = max(1, len(prompt_text) // 4)
        completion_tokens = max(1, len(raw_text) // 4)

        logger.debug(
            f"MockAdapter call #{self._call_count}: intent={intent} "
            f"prompt_tokens={prompt_tokens} completion_tokens={completion_tokens}"
        )

        return TAPResponse(
            raw_text=raw_text,
            usage={
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
            },
            finish_reason="stop",
        )

    # ----- core stream -----

    async def stream(self, compiled: CompiledPrompt, model: str) -> AsyncIterator[str]:
        """Stream a compiled prompt from the mock adapter.

        Yields chunks of the mock response with small delays to simulate
        streaming behaviour.
        """
        response = await self.send(compiled, model)
        chunk_size = 10
        text = response.raw_text or ""
        for i in range(0, len(text), chunk_size):
            yield text[i : i + chunk_size]
            await asyncio.sleep(0.02)

    # ----- capabilities -----

    @property
    def capabilities(self) -> dict:
        return {
            "streaming": True,
            "tool_calling": False,
            "max_context_tokens": 100000,
            "mock": True,
        }


# Register with TAPAdapterRegistry
TAPAdapterRegistry.register("mock", MockAdapter)
