"""examples.full_agent — Complete Design→Plan→Execute→Review pipeline demo

This entry point wires together the EventBus components from the full_agent
package into a complete pipeline. Uses MockAdapter so it runs without API keys.

Pipeline flow:
    requirement → DesignGenerator → design_ready
                                    ↓
                PlanGenerator     ← design_ready → plan_ready
                                                  ↓
                Reviewer          ← plan_ready  → review_result
                                                  ↓
                ChecklistGenerator ← plan        → checklist_ready

Usage:
    python -m examples.full_agent
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field

from teragent.core.adapters.mock import MockAdapter
from teragent.core.compiler import TAPCompilerRegistry
from teragent.core.provider import ModelProvider
from teragent.event_bus import EventBus

from .checklist_generator import ChecklistGenerator
from .design_generator import DesignGenerator
from .plan_generator import PlanGenerator
from .reviewer import Reviewer

logging.basicConfig(
    level=logging.INFO,
    format="%(name)s | %(levelname)s | %(message)s",
)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# ChineseMockAdapter — returns Chinese content that passes the validators
# ---------------------------------------------------------------------------
# The default MockAdapter returns English section headers (e.g., "Background &
# Motivation"), but DesignGenerator/PlanGenerator validators require Chinese
# section names (e.g., "背景与动机").  This subclass provides mock responses
# that satisfy the validators so the full pipeline completes without retries.
# ---------------------------------------------------------------------------


class ChineseMockAdapter(MockAdapter):
    """MockAdapter subclass that returns Chinese content matching validators.

    Overrides _get_mock_response to provide properly formatted Chinese mock
    content for design and plan intents, so the pipeline validators pass on
    the first attempt (no retries needed).
    """

    @staticmethod
    def _get_mock_response(intent: str, task_id: str = "unknown") -> str:
        """Return Chinese mock responses that pass the pipeline validators."""
        mock_responses: dict[str, str] = {
            "design": (
                "# DESIGN.md\n"
                "\n"
                "## 背景与动机\n"
                "需要一个简单的任务管理系统来追踪项目进度，"
                "支持增删改查和状态追踪。\n"
                "\n"
                "## 设计目标\n"
                "- 简洁易用的命令行界面\n"
                "- 任务增删改查与状态追踪\n"
                "- 持久化存储（SQLite）\n"
                "\n"
                "## 技术选型\n"
                "Python 3.10+，asyncio + aiosqlite\n"
                "\n"
                "## 目录结构\n"
                "task_manager/\n"
                "  __init__.py\n"
                "  main.py\n"
                "  models.py\n"
                "  storage.py\n"
                "\n"
                "## 核心接口契约\n"
                "```python\n"
                "class TaskManager:\n"
                "    async def add_task(self, title: str) -> Task: ...\n"
                "    async def list_tasks(self) -> list[Task]: ...\n"
                "    async def complete_task(self, task_id: str) -> None: ...\n"
                "```\n"
            ),
            "plan": (
                "### 1.1 实现数据模型\n"
                "- **输出文件排他声明**: task_manager/models.py\n"
                "- **前置依赖**: None\n"
                "- **实现要点**: 定义 Task dataclass，包含 id/title/status 字段\n"
                "- **优先级**: Required\n"
                "\n"
                "### 1.2 实现存储层\n"
                "- **输出文件排他声明**: task_manager/storage.py\n"
                "- **前置依赖**: 1.1\n"
                "- **实现要点**: 基于 aiosqlite 的 CRUD 操作\n"
                "- **优先级**: Required\n"
                "\n"
                "### 1.3 实现命令行入口\n"
                "- **输出文件排他声明**: task_manager/main.py\n"
                "- **前置依赖**: 1.2\n"
                "- **实现要点**: argparse + asyncio.run 入口\n"
                "- **优先级**: Required\n"
            ),
            "review": "APPROVE — 设计合理，可以继续实施。",
            "checklist": (
                "- [x] 1.1 实现数据模型\n"
                "- [x] 1.2 实现存储层\n"
                "- [ ] 1.3 实现命令行入口"
            ),
            "code_generation": (
                f'<file path="mock_output.py">\n'
                f"# Auto-generated by ChineseMockAdapter\n"
                f"def main() -> None:\n"
                f'    """Mock implementation for task: {task_id}"""\n'
                f"    pass\n"
                f"</file>"
            ),
        }
        return mock_responses.get(intent, mock_responses["code_generation"])


# ---------------------------------------------------------------------------
# Simple plan object for ChecklistGenerator
# ---------------------------------------------------------------------------
# ChecklistGenerator.on_request() expects a plan-like object with a .tasks
# attribute where each task has .id, .title, .status, .output_files.
# ---------------------------------------------------------------------------


@dataclass
class SimpleTask:
    """Minimal task object compatible with ChecklistGenerator."""

    id: str = ""
    title: str = ""
    status: str = "pending"
    output_files: list[str] = field(default_factory=list)


@dataclass
class SimplePlan:
    """Minimal plan object compatible with ChecklistGenerator."""

    tasks: list[SimpleTask] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------


async def main() -> None:
    """Run the complete Design→Plan→Review→Checklist pipeline."""
    print("=" * 70)
    print("TerAgent Full Agent Pipeline Demo")
    print("  Design → Plan → Review → Checklist")
    print("  (Using ChineseMockAdapter — no API keys required)")
    print("=" * 70)

    # ------------------------------------------------------------------
    # 1. Create provider with ChineseMockAdapter
    # ------------------------------------------------------------------
    compiler_cls = TAPCompilerRegistry.get("default")
    provider = ModelProvider(
        compiler=compiler_cls(),
        adapter=ChineseMockAdapter(delay=0.05),
        model="mock-model",
    )
    print(f"\n✓ Provider created: {provider}")

    # ------------------------------------------------------------------
    # 2. Create EventBus and wire all 4 components
    # ------------------------------------------------------------------
    bus = EventBus()

    # DesignGenerator: subscribes to "request_design"
    #                 emits "design_ready" / "design_generation_failed"
    design_gen = DesignGenerator(bus, provider)

    # PlanGenerator: subscribes to "request_plan_generation" / "request_replan"
    #                emits "plan_ready" / "plan_generation_failed"
    plan_gen = PlanGenerator(bus, provider)

    # Reviewer: subscribes to "request_design_review" / "request_plan_review"
    #           emits "review_result"
    reviewer = Reviewer(bus, model=provider, llm_review=True)

    # ChecklistGenerator: subscribes to "request_checklist"
    #                     emits "checklist_ready" / "checklist_issues_detected"
    checklist_gen = ChecklistGenerator(bus)

    # ------------------------------------------------------------------
    # 3. Add listeners to capture and display results at each stage
    # ------------------------------------------------------------------
    results: dict[str, object] = {}

    async def on_design_ready(content: str) -> None:
        results["design"] = content
        print(f"\n{'─' * 60}")
        print("📐 DESIGN generated successfully:")
        for line in content.split("\n")[:10]:
            print(f"   {line}")
        if content.count("\n") > 10:
            print(f"   ... ({content.count(chr(10)) - 10} more lines)")
        print(f"   [{len(content)} chars total]")

    async def on_design_failed(error: str) -> None:
        results["design_error"] = error
        print(f"\n⚠️  Design generation failed: {error[:120]}")
        print("   (This is expected when using MockAdapter with English responses)")

    async def on_plan_ready(content: str) -> None:
        results["plan"] = content
        print(f"\n{'─' * 60}")
        print("📋 PLAN generated successfully:")
        for line in content.split("\n")[:10]:
            print(f"   {line}")
        print(f"   [{len(content)} chars total]")

    async def on_plan_failed(error: str) -> None:
        results["plan_error"] = error
        print(f"\n⚠️  Plan generation failed: {error[:120]}")

    async def on_review_result(approved: bool, notes: str, suggestions: list[str]) -> None:
        results["review_approved"] = approved
        results["review_notes"] = notes
        results["review_suggestions"] = suggestions
        verdict = "✅ APPROVED" if approved else "❌ REJECTED"
        print(f"\n{'─' * 60}")
        print(f"🔍 REVIEW: {verdict}")
        print(f"   Notes: {notes[:120]}")
        if suggestions:
            for s in suggestions[:5]:
                print(f"   💡 {s[:100]}")

    async def on_checklist_ready(checklist: str) -> None:
        results["checklist"] = checklist
        print(f"\n{'─' * 60}")
        print("✔️  CHECKLIST:")
        for line in checklist.split("\n"):
            print(f"   {line}")

    bus.on("design_ready", on_design_ready)
    bus.on("design_generation_failed", on_design_failed)
    bus.on("plan_ready", on_plan_ready)
    bus.on("plan_generation_failed", on_plan_failed)
    bus.on("review_result", on_review_result)
    bus.on("checklist_ready", on_checklist_ready)

    wired_events = bus.get_event_names()
    print(f"\n✓ EventBus wired with {len(wired_events)} event subscriptions")
    print(f"  Event types: {wired_events}")

    # ------------------------------------------------------------------
    # 4. Run the pipeline: requirement → design → plan → review → checklist
    # ------------------------------------------------------------------

    # Stage 1: Design — generate design document from requirement
    print(f"\n{'=' * 60}")
    print("Stage 1: DESIGN (requirement → design document)")
    print(f"{'=' * 60}")
    requirement = "构建一个简单的任务管理系统，支持任务增删改查和状态追踪"
    print(f"  Requirement: {requirement}")
    await bus.emit_and_wait("request_design", requirement)
    await asyncio.sleep(0.1)  # Allow nested emit handlers to complete

    # Stage 2: Design Review — LLM reviews the design
    if "design" in results:
        print(f"\n{'=' * 60}")
        print("Stage 2: DESIGN REVIEW (LLM reviews the design)")
        print(f"{'=' * 60}")
        await bus.emit_and_wait("request_design_review", results["design"])
        await asyncio.sleep(0.1)

    # Stage 3: Plan — generate plan from approved design
    if "design" in results:
        print(f"\n{'=' * 60}")
        print("Stage 3: PLAN (design → task plan)")
        print(f"{'=' * 60}")
        await bus.emit_and_wait("request_plan_generation", results["design"])
        await asyncio.sleep(0.1)

    # Stage 4: Plan Review — LLM reviews the plan
    if "plan" in results:
        print(f"\n{'=' * 60}")
        print("Stage 4: PLAN REVIEW (LLM reviews the plan)")
        print(f"{'=' * 60}")
        await bus.emit_and_wait("request_plan_review", results["plan"])
        await asyncio.sleep(0.1)

    # Stage 5: Checklist — deterministic checks on the plan
    print(f"\n{'=' * 60}")
    print("Stage 5: CHECKLIST (deterministic code checks)")
    print(f"{'=' * 60}")
    plan_obj = SimplePlan(
        tasks=[
            SimpleTask(
                id="1.1",
                title="实现数据模型",
                status="completed",
                output_files=["task_manager/models.py"],
            ),
            SimpleTask(
                id="1.2",
                title="实现存储层",
                status="completed",
                output_files=["task_manager/storage.py"],
            ),
            SimpleTask(
                id="1.3",
                title="实现命令行入口",
                status="pending",
                output_files=["task_manager/main.py"],
            ),
        ]
    )
    await bus.emit_and_wait("request_checklist", plan_obj)
    await asyncio.sleep(0.1)

    # ------------------------------------------------------------------
    # 5. Summary
    # ------------------------------------------------------------------
    print(f"\n{'=' * 70}")
    print("Pipeline Complete!")
    print(f"{'=' * 70}")
    print(f"  Design:      {'✓' if 'design' in results else '✗'}")
    print(f"  Plan:        {'✓' if 'plan' in results else '✗'}")
    print(
        f"  Review:      {'✅ Approved' if results.get('review_approved') else '❌ Rejected' if 'review_approved' in results else '✗'}"
    )
    print(f"  Checklist:   {'✓' if 'checklist' in results else '✗'}")
    print(f"\n  EventBus events fired: {len(bus.get_event_history())}")
    event_names = [e[0] for e in bus.get_event_history()]
    print(f"  Event sequence: {event_names}")

    print(
        f"\n  Components used: DesignGenerator, PlanGenerator, Reviewer, ChecklistGenerator"
    )
    print(
        f"  Adapter: ChineseMockAdapter (extends MockAdapter with Chinese content)"
    )
    print(
        f"  Tip: Replace ChineseMockAdapter with a real adapter (openai_compatible,"
    )
    print(
        f"       anthropic_native, etc.) and provide API keys for production use."
    )
    print()


if __name__ == "__main__":
    asyncio.run(main())
